### ISSUE TITLE
Server error when searching for 'ayahciyiniw'

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#117]
Reproduce by going here: http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=ayahciyiniw

**Comment by eddieantonio** [comment]
Curiously, it still works if you delete a single letter: http://altlab.ualberta.ca/itwewina/crk/eng/?lookup=ayahciyini

**Comment by eddieantonio** [comment]
I implemented a temporary solution until #120 is resolved.

This crash happens because itwêwina is trying to match the animacy of the analysis with the animacy of the dictionary entry. However, as #120 notes, some nouns don't specify animacy, and thus, we cannot match anything with the analysis. Instead of crashing, I decided that such dictionaries will NEVER match with any analysis, so the floating linguistic breakdown thing will NOT be associated with any search result.

Closing for now.

**Comment by aarppe** [comment]
This is because ayahciyiniw is not in the original comparison files: gloss_comparison_full.txt and MD_vs_CW_gloss_comparison_full_autonorm_min-morph, for whatever reason - likely that an earlier version of the FST (pre-rerevamp in 2016) was not able to analyze it, and thus it was presumed it wouldn't therefore be in CW.

Because the entry is not in the comparison file, there is no judgement of the similarity of the glosses, and thus not attempt to aggregate them - so an example of what itwêwina would look like without the content comparison.

There may be other words like it, that the current FST could recognize, and which co-occur in both sources.
