### ISSUE TITLE
Update dictionary source (crkeng*.xml) and crk FST

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#210]
@eddieantonio If we have issues with the new itwêwina, then for the time being we should update the dictionary source and the crk FST here in the old itwêwina.

The Cree-to-English dictionary source can be found on sapir in: `/data/exps/itwewina/neahtta/dicts/crkeng-20200208.xml`

Since the old itwêwina uses HFST, the new crk FST should be usable as is.

Of course, we'd have to recreate the `engcrk.*.xml` to match the `crkeng.*.xml` one, but we might make do with just the latter for now.

**Comment by eddieantonio** [comment]
I've updated the dictionary contents, but I'm not restarting the server until UAlbertaALTLab/cree-intelligent-dictionary#274 is resolved.

**Comment by eddieantonio** [comment]
So I updated the dictionary and FST anyway, but, as expected, âyiman simply is missing a definition:

![Screen Shot 2020-02-18 at 10 47 23 AM](https://user-images.githubusercontent.com/2294397/74763011-2de94880-523c-11ea-8e0e-727b8b304845.png)

https://altlab.ualberta.ca/itwewina/crk/eng/?lookup=ayiman

So this issue is still blocked by UAlbertaALTLab/cree-intelligent-dictionary#274

**Comment by eddieantonio** [comment]
This is fixed using the manually edited XML.

See this URL to see for yourself! https://altlab.ualberta.ca/itwewina/crk/eng/?lookup=ayiman
