### ISSUE TITLE
FST issue: does not produce epenthetic (h) in conjunct forms with vowel-initial lemmas

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#24]
For example, try "itohtêw":
<img width="1217" alt="captura de pantalla 2018-07-16 a las 6 09 30 p m" src="https://user-images.githubusercontent.com/2294397/42789598-69cad67c-8923-11e8-9751-d4770b037ed1.png">

What I expected:
**ê-hitohtêyahk**
What I got:
**ê-itohtêyahk**

**Comment by aarppe** [comment]
This behavior is by design. You can either use the hyphen, or the epenthetic -h- (substandard), but not both.

Indeed, the epenthetic element can result as a -y- as well, and because of that the SRO (according to Arok and Jean) prefers the hyphen which can be replaced by any appropriate epenthetic element, when the word is pronounced (and we've indeed observed free variation on that position.

So that we don't generate an epenthesized  form in every slot, the -h- epenthesized form is considered substandard, but it is recognized nevertheless, cf.

e-itohtet
e-itohtet	PV/e+itohtêw+V+AI+Cnj+Prs+3Sg	0.000000

ehitohtet
ehitohtet	PV/e+itohtêw+V+AI+Cnj+Prs+3Sg+Err/Orth	0.000000

As discussed earlier, the YAML files are Scripture in these matters, cf. for atoskêw.

~/giella/branches/crk/test/src/gt-norm-yamls/V-AI-atoskew_gt-norm.yaml

The NS materials do rather use an epenthetic -h-, but that is not strictly according to SRO standard (according to Arok), and if you use it, you can't also use the hyphen. So we could in principle produce both forms, but for practical reasons (Arok's griping) we have selected to output only the non-epenthesized forms.

**Comment by eddieantonio** [comment]
This isn't a bug in the FST; it's a bug in my understanding! Closing.
