### ISSUE TITLE
Fix generation of crkeng-cans XML dictionary

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#62]
`/neahtta/tools/filter_xpath.py` is used from within `/neahtta/dicts/Makefile` to derive the Cans version of crkeng.xml.

However, this script seems to assume each entry has a unique stem. This is not the case. Instead, fix fix the stems based on object identity.

Fixing this _should_ fix #60.

**Comment by eddieantonio** [comment]
@aarppe It occurs to me that at this point, I can prevent the conversion of the **stem to syllabics**, and leave the stem in SRO, even in the syllabics dictionary. Should I do this instead?

**Comment by eddieantonio** [comment]
As a follow-up to #60, here's how the dictionary looks with the slightly fixed script, with stems in syllabics:

ka-kî-awâsisîwiyân:
![captura de pantalla 2018-09-17 a las 2 59 07 p m](https://user-images.githubusercontent.com/2294397/45650046-4c1ca900-ba8a-11e8-9982-d6e2917ba732.png)

nikî-nitawi-kiskinwahamakosin:
![captura de pantalla 2018-09-17 a las 2 59 46 p m](https://user-images.githubusercontent.com/2294397/45650051-4fb03000-ba8a-11e8-93d0-358b93ac23f7.png)

**Note**: NDS did not have to be changed; simply the script that converts the SRO dictionary to Cans.

**Comment by aarppe** [comment]
Whether we present the stem according to the selected orthography (i.e. in syllabics above) or in SRO would be something that I'd base our decision on alpha user feedback.

I quite like the presentation of stems in syllabics. I suspect Arok has an opinion, and there might be an Algonquianist tradition here (some might hold the view that since the stems are not actual words, and one doesn't have the hyphen in syllabics to indicate their stemness, then stems should not be presented in syllabics but in SRO instead).

We could end up making this into a option that the user can select, but we'd have to choose carefully which presentation issues are truly worthy/necessary as options, not to end up with too many.

**Comment by eddieantonio** [comment]
Alright. I'm making the executive decision to display stems in SRO, even when the display orthography is syllabics.

> We could end up making this into a option that the user can select, but we'd have to choose carefully which presentation issues are truly worthy/necessary as options, not to end up with too many.

This is a feature request that we can implement down the road, when our alpha testers request it.

**Comment by aarppe** [comment]
SRO stems will at least be consistent with the orthography of the linguistic analysis, in particular as the preverbs are presented in SRO.

What did cross my mind but which I didn't write previously is that that presenting stems in syllabics would warrant for syllabic presentation of the preverbs as well. But we can consider that once we start soliciting and getting feedback.

**Comment by eddieantonio** [comment]
As of b2cc30a0, stems are no longer converted to syllabics. Closing.
