### ISSUE TITLE
Regenerate Cree->English dictionary using revised dictionary XML format

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#89]
Regenerate the dictionary incorporating both Arok's dictionary and the Maskwacîs dictionary. Use the new format agreed upon in #61 and documented in #87.

**EDIT**: the documentation now lives here: https://github.com/UAlbertaALTLab/itwewina/blob/development/docs/xml-dictionary.md#the-xml-dictionary-format

**Comment by aarppe** [comment]
First pass done and placed in the non-public part of the repository, based on comparisons by KS and standardization of lexical entries by AA. While comparisons needs further work, currently about half of MD incorporated in a crude manner.

For the sake of getting started, only cases where MD and CW English gloss is exactly the same (sources="MD CW"), or cases where MD and CW English glossed are considered two meaning groups (with two separate `<mg>` elements); no cases yet of MD and CW English translations presented within the same and only one meaning group (with only one `<mg>` element).

Incorporation of MD inflected forms requires some scripting to get the correct CW POS and lexical category code ([NV]XX[1-5]) in order to be able generate paradigms (currently not simply making use of a field in the comparison file by required aggregation of data from multiple sources in a non-trivial way).

**Comment by eddieantonio** [comment]
I'm gonna call this done for now, and we can revisit it later and improve upon it. For now though, this should be enough for me to write tests and redeploy!

**Comment by aarppe** [comment]
The representational option for `acosis` (for two translation groups within one meaning group) was deliberately omitted from the first implementation of the creation of the new combined crk2eng dictionary source XML code (I think primarily having to deal with some complex interpretation of the dictionary comparison file). A solution is being currently devised.
