### ISSUE TITLE
Dynamically link to recordings in the Recordings Validation app

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/itwewina#92]
Now that UAlbertaALTLab/recording-validation-interface/issues/27 provides a simple API to retrieve relevant recordings, enable itwêwina to embed them into the page.

Tasks
------

 - [x] Write integration test: mock API endpoint
 - [x] How does SoundManager 2 do it? 🤢 
 - [x] HTTP GET to API (with jQuery)
 - [x] Create `<audio>` tags (with jQuery) and add them to the page
 - [x] Get a few word forms and the API endpoint into the search and details pages
 - [x] Implement reasonable defaults for POSs I don't know about.
 - [x] Create config option for the API
 - [x] Refactor tests
 - [x] Document the integration... somewhere
 - [x] ~~Refactor gross function in `views/setup.py`~~
 - [x] Remove SoundManager2

**Comment by eddieantonio** [comment]
@aarppe: For each PoS, what are some common word forms that our speakers would produce?

I know that for verbs, the speakers tended to give conjunct form, but anecdotally, I see 1Sg.Prs.Independent was quite common too. Any other word forms I should search for too?

**Comment by eddieantonio** [comment]
This is finished as of  702892d

**Comment by aarppe** [comment]
For the record, what we have observed in terms of inflected forms in single-word elicitation is primarily getting first the Conjunct+Present/Neutral+3Sg form, instead of the Independent+Present/Neutral+3Sg form. In some cases, we might also get the literal 'you (sg)' form (in the conjunct), but this applies mostly for the example sentences.

For the nouns, we would generally be getting the singular non-possessed forms (where the bulk of the nouns are non-dependent ones).

For dependent nouns, when Unspecified possession is possible, we might get both the mi- (PxX) and o- (Px3Sg) forms. I have know clear recollection of what was the preferred form for the kinship dependent nouns, though presumably forms possessed by Px1Sg or Px2Sg would probably be the most likely ones provided by the speakers (i.e. nôhkom or kôhkom).
